name: "CarConnectivity Addon"
version: "0.0.3"
slug: "carconnectivity-addon"
description: "Addon version of Carconnectivity made by Till (see https://github.com/tillsteinbach/CarConnectivity) throught MQTT"
panel_icon: "mdi:car-wireless"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ingress: false
init: false
options:
  connector_username_seatcupra: "mail1@mail.com"
  connector_password_seatcupra: "password1"
  connector_spin_seatcupra: "1234"
  connector_interval_seatcupra: 600
  connector_username_skoda: ""
  connector_password_skoda: ""
  connector_spin_skoda: ""
  connector_interval_skoda: 600
  connector_username_vw: ""
  connector_password_vw: ""
  connector_spin_vw: ""
  connector_interval_vw: 600
  connector_username_trionity: ""
  connector_password_trionity: ""
  connector_spin_trionity: ""
  connector_interval_trionity: 600
  mqtt_username: "mqtt"
  mqtt_password: "passwordmqtt"
  mqtt_broker: "192.168.1.52"
  log_level: list(info|warning|error|debug)
schema:
  connector_username_seatcupra: email?
  connector_password_seatcupra: password?
  connector_interval_seatcupra: int(60,3600)?
  connector_spin_seatcupra: match(^\d{4}$)?
  connector_username_skoda: email?
  connector_password_skoda: password?
  connector_interval_skoda: int(60,3600)?
  connector_spin_skoda: match(^\d{4}$)?
  connector_username_vw: email?
  connector_password_vw: password?
  connector_interval_vw: int(60,3600)?
  connector_spin_vw: match(^\d{4}$)?
  connector_username_trionity: email?
  connector_password_trionity: password?
  connector_interval_trionity: int(60,3600)?
  connector_spin_trionity: match(^\d{4}$)?
  mqtt_username: str
  mqtt_password: password
  mqtt_broker: str
  log_level: list(info|warning|error|debug)